### PR TITLE
Remove remaining CUB data

### PR DESCRIPTION
**Pull request by MrPrimate**
CUB condition swaps:
* Animal Friendship
* Hypnotic Pattern
* Sunbeam
* Grease
* Web
* Hold Person
* Hold Monster

Macro rewritten:
* Divine Word
* Hideous Laughter

Removed duplicate Hideous Laughter.
Removed excessive/dead flag data to reduce item sizes

### CODE REVIEW

**Comment by thatlonelybugbear** [comment]
~~FYI, Just grabbed the forked spells.db and saw that there is still a duplicate Hideous Laughter in there @MrPrimate~~

**Comment by MrPrimate** [comment]
@thatlonelybugbear one of these is a macro one, one is without macro, I removed the duplicate macro entry.

**Comment by thatlonelybugbear** [comment]
Ah OK sorry. Just scanned through and saw that there was a `cub.addCondition` for Prone in the (now I know) Macro version of the Hideous Laughter and thought it was just forgotten in there!

**Comment by MrPrimate** [comment]
~~Ah! I think it can probably be removed TBH - with AboutTime and the Overtime effect I _think_ the macro is now redundant.~~  So you probably want the maro to do the save when damaged - I'll take a look.

**Comment by thatlonelybugbear** [comment]
I dont use it tbh (the macro one), just scanned through the changes, and it caught my eye cause I read about the duplicate Hideous Laughter entries in your changelogs and thought whoops there is still another Hideous Laughter entry :P

Didn't even register that the 2 might be serving different purposes !

**Pull request merged**
